export const Icon = {
  Left: require('./Left.png'),
  Right: require('./Right.png'),
  Profile: require('./Profile.png'),
  Product: require('./Product.png'),
  Receipt: require('./Receipt.png'),
  Notification: require('./Notification.png'),
  Profile_outline: require('./Profile_outline.png'),
  Product_outline: require('./Product_outline.png'),
  Receipt_outline: require('./Receipt_outline.png'),
  Notification_outline: require('./Notification_outline.png'),
  Search: require('./Search.png'),
  Show: require('./Show.png'),
  Hide: require('./Hide.png'),
  Close: require('./Close.png'),
  Resize: require('./Resize.png'),
  Calendar: require('./Calendar.png'),
  Plus: require('./Plus.png'),
  Filter: require('./Filter.png'),
  Checkbox: require('./Checkbox.png'),
  Checkbox_outline: require('./Checkbox_outline.png'),
  Truck: require('./Truck.png'),
  People: require('./People.png'),
  Cloud_down: require('./Cloud_down.png'),
  Edit: require('./Edit.png'),
  Unlock: require('./Unlock.png'),
  Logout: require('./Logout.png'),
  PlusGreen: require('./PlusGreen.png'),
  MinusGreen: require('./MinusGreen.png'),
  Tick: require('./TickGreen.png'),
  Double_Tick: require('./Double_Tick.png'),
  Single_Tick: require('./Single_Tick.png'),
  Analyze: require('./Analyze.png'),
  Book: require('./Book.png'),
  Scan: require('./Scan.png'),
  Cart: require('./Cart_outline.png'),
  Delete: require('./Delete.png'),
};

export type IconType = typeof Icon;
